### ISSUE TITLE
Support shared transactions

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store#150]
Based on the discussion in https://github.com/prooph/event-store-doctrine-adapter/issues/3 with @Richtermeister we should think about a way to support his use case.

Atm I see two options:

1. Add a new method to the event store to `enableTransactionSlaveMode` (just a rough idea for the name). If slave mode is enabled the event store does not **begin, commit or rollback** a transaction using its adapter but still triggers the related events like `commit.post`.
2. Provide a decorator for the doctrine event store adapter which does not implement the `CanHandleTransaction` interface but only the `Adapter` interface. The decorator would pass all stream manipulation and read operations to the normal doctrine adapter but the event store would not call the related transaction methods on the adapter.

What do you think? @Richtermeister, @prooph/components-core

**Comment by prolic** [comment]
i don't have much time right now. i need to think about it for a while to find a clean solution. i hope this has no hurry.

**Comment by Richtermeister** [comment]
Nope, no hurry. Thank you guys for being open to the idea. I will think about this as well and try to submit a PR shortly.

**Comment by codeliner** [comment]
@prolic , @Richtermeister Today I've tried option 2 - a DoctrineEventStoreAdapter decorator that does not implement `CanHandleTransaction`. 

Here is the [decorator](https://gist.github.com/codeliner/b869bd43445cb06f0d10), its factory, configuration and a short example.

I really like this approach as the event-store supports it without changes and it is exactly what we want: a shared doctrine connection used in the event store adapter without effecting the rest of the system. You would need to use an own transaction manager but it is really simple to write one.
What do you think?

**Comment by prolic** [comment]
I like it, no need for changing something in event store, so +1
Am 14.02.2016 16:47 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by rommsen** [comment]
@codeliner / @prolic : I would like to reopen this. Your decorator seems to work really well but I think that the EventStore is not implemented consistently.

The whole point with the decorator is that the adapter is not handling the transactions but nevertheless  triggers the related events like commit.post.

This works fine for beginTransaction and commit because transaction handling is ignored when the adapter does not implement `canHandleTransaction` but it breaks in rollback because  [here](https://github.com/prooph/event-store/blob/master/src/EventStore.php#L371) it throws an exception if the interface is not implemented.

I am not sure if I should just not call rollback in an error case but I feel that the whole transaction handling should be consistent.

**Comment by codeliner** [comment]
@rommsen I thought about the same while playing with the decorator idea. My conclusion was that it is more important to tell a developer: "Hey you want to roll back but your adapter does not provide such functionality!". My reasoning: `EventStore::beginTransaction` and `EventStore::commit` are still valid calls because the event store transaction collects all recorded events and publish them on `commit.post`. When the adapter does not provide transaction support the event store transaction just can not be rolled back. So yes, don't call `EventStore::rollback` but roll back only the database transaction. However, I'm open for discussion. It would be possible to change the behavior as we want to release a new major version of the event store anyway.

**Comment by rommsen** [comment]
@codeliner in my optionioin there are two reasons to make `rollback` consistent with `beginTransaction` and `commit`

1. `rollback` sets `inTransaction` back to false. So if I don't call `rollback` and have a long running process I leave the `EventStore` in a kind of inconsistent state
2. We are using Monologs [FingersCrossedHandler](https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md#wrappers--special-handlers) to have as much context as possible when an error occurs. It stores all logs in a buffer and only writes them to the log in case of an error. The event system in prooph is a perfect match for a logger plugin, which logs every state of the MessageBus and EventStore. Not calling rollback would unnecessarily reduce the number of information in case of an error.
3. (bonus) it just feels inconsistent :smile:

**Comment by codeliner** [comment]
very good points @rommsen . You convinced me. We can change the behavior with the next major release. @prolic what do you think?

**Comment by prolic** [comment]
agree

**Comment by codeliner** [comment]
Extracted roll back issue into a separate issue, see #169
