### ISSUE TITLE
Argument 1 passed to AppendIterator::append is not Iterable

### ISSUE THREAD

**Issue by basz** [prooph/event-store#158]
Fatal error: Uncaught TypeError: Argument 1 passed to AppendIterator::append() must implement interface Iterator, array given in .../vendor/prooph/event-store/src/EventStore.php:150

The value is an array, not an ArrayObject as it seems to expect.

I'm have a simple Aggregate and the event contains simple logic. I run two command after each other that should create a new event. whenever i use the same uuid for the first one, it gets rejected (like it should) in the handler. and only then this error occurs.

```
    public function __invoke(RegisterUser $command)
    {
        $user = $this->repository->get($command->userId());

        if ($user) {
            throw new DomainAssertionException('A user with that user_id has already been registered');
        }

        $user = User::registerUserWith(
            $command->userId(),
            $command->emailAddress(),
            $command->passwordHash(),
            $command->displayName()
        );

        $this->repository->add($user);
    }
```

bug or am i missing something?

**Comment by prolic** [comment]
Imho this check:

   $user = $this->repository->get($command->userId());

    if ($user) {
        throw new DomainAssertionException('A user with that user_id has already been registered');
    }

is not neccessary. The uuid is unique anyway. Also there is a unique constraint on database side. However there is indead a bug, thanks for finding it! :-)
