### ISSUE TITLE
Optimize package for PHP7

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store#170]
New version of prooph event store will support PHP 7 only

**Comment by mikemix** [comment]
New versions are introduced so fast I cannot keep up. Almost like Firefox or Chrome releases ;)

**Comment by codeliner** [comment]
continuous delivery ;) If we don't release new versions every few month people would start thinking that the project is dead :P

 Anyway, current versions are stable and can be used in production. New versions just take the next step and make use of the wonderful features provided by PHP7(.1)

**Comment by mikemix** [comment]
Which version will be required? ^7.0 or ^7.1

**Comment by prolic** [comment]
@mikemix you can use the 6.3 release right away, there won't be much changes needed, when updating to 7 (probably even zero!)

currently i am planning with 7.0, but when 7.1 comes out soon enough, we'll reconsider using that.
