### ISSUE TITLE
Remove .pre and .post action event hooks

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#186]
Replace with something much simpler:

```
foreach ($this->preCallbacks as $callback) {
    $callback($args);
}
$this->commit();
foreach ($this->postCallbacks as $callback) {
    $callback($args);
}
```

Note: This is not meant for service-bus

**Comment by sandrokeil** [comment]
Does this mean we don't need an `ActionEventEmitter` here anymore? But `rollback` is not in the example. I think it is only worth it, if we remove `ActionEventEmitter`. But then we lost some flexibility. I'm not sure if someone extended the `EventStore` with own events. 

This could improve performance (less function calls).

**Comment by prolic** [comment]
Yes the idea is to remove the actioneventemitter in the event store for better performance. It still has to be measured if this is worth it.

**Comment by sandrokeil** [comment]
We should add first [phpbench benchmarks](https://github.com/phpbench/phpbench) to develop. This is also interesting for further improvements.

**Comment by bweston92** [comment]
I must say I like the whole event emitting, but maybe for event store it isn't needed as there is just 2 events fired.

**Comment by bweston92** [comment]
@prolic when will a PR be submitted for this? I will then submit a PR to snapshotter to plugin
.

**Comment by Ocramius** [comment]
You can probably get rid of `.pre` and `.post` if `$this->commit();` is moved to a listener itself btw. Still allows pre/post this way, but via priority.

If all you wanted to do is to call these endpoints manually due to performance, I don't think that doing it yourself is a good idea, as you're changing well known/interoperable API

**Comment by bweston92** [comment]
@Ocramius I think it is more down to the fact the event store only has 2 events so might be overkill to use the event emitter.

**Comment by prolic** [comment]
see: https://github.com/prooph/event-store/pull/211

1) here we have a special interfaces for event triggering
2) we use only one event (no .pre & .post), the core logic itself is a listener with default priority

**Comment by prolic** [comment]
There is now a single event hook and you have to use priority to have pre and post. Other than that, you're free to implement the event store interface yourself without an ActionEventEmitter.
