### ISSUE TITLE
Use aggregate root marker interface for PHP 7.1

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store#188]
Is it a good idea to use an aggregate root marker interface so we can type hint against it e.g. `\Prooph\EventStore\Aggregate\AggregateRepository::getAggregateRoot() : ?AggregateRoot`. The current return type is specified with `null|object`.

**Comment by prolic** [comment]
For the event store itself this is not needed. If this is required, this should be part of userland code.

**Comment by sandrokeil** [comment]
Alright, sounds reasonable.
