### ISSUE TITLE
Fix composer

### ISSUE THREAD

**Issue by timiTao** [prooph/event-store#189]
Can't use alone EventStore, as composer don't have all needed dependencies.

```
<b>Fatal error</b>:  Trait 'Interop\Config\ConfigurationTrait' not found in
<b>/vagrant/vendor/prooph/event-store/src/Container/EventStoreFactory.php</b> on line 
```

**Comment by sandrokeil** [comment]
Please take a look at the [`composer.json`](https://github.com/prooph/event-store/blob/master/composer.json#L46) file. This is a suggestion and only needed if you use the factories. It's not needed, e.g. If you use Symfony.

**Comment by prolic** [comment]
The container interop factories are optional. So this dependency is only
optional, too.

Am 21.10.2016 20:37 schrieb "timiTao" <notifications@github.com>:
