### ISSUE TITLE
RFC Remove Adapter::replay method

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#190]
I am thinking about removing the `replay` method on the Adapter interface (as well as the related `CompositeIterator`).

Imho this makes not much sense and using `CompositeIterator` with millions of streams will be a big performance problem.

Therefore I suggest using another replay strategy based on the existing `load` method on the adapter interface. This can be added to the event-store-bus-bridge repository as new feature.

thoughts @codeliner ?

**Comment by codeliner** [comment]
not sure... With the `load` method you can only load the history of a single stream. Replay joins events of different streams and puts them in chronological order. How do you want to achieve the same with the `load` method?

I agree, that replay becomes a problem when you have many streams. You definitely need another strategy then but for simpler use cases it is a good option and it is already there. So why remove it. Or can we move it to its own package so that not every adapter is forced to implement the replay method?

And why `event-store-bus-bridge`?

**Comment by prolic** [comment]
Sorry I should have provided more information in the description.

First of all the `replay` method suggests, that this is the right way to do it as it's part of the adapter interface - but as I said this really leads to serious problems with a lot of streams (especially with one stream per aggregate).

Here my `new` example on how to make replays:

The order is very important (sometimes) and sometimes it's not. Here's why....

Let's make replay by example: I want to replay all user-streams and all friendship-streams (user-to-user-relations). This would look like this:
```
foreach ($db->fromCategory('user') as $userStream) {
    $this->replay($userStream);
}
foreach ($db->fromCategory('friends') as $friendStream) {
      $this->replay($friendStream);
}
```

So replaying one user after the other really does the job. From the standpoint of a given user, he's a single aggregate and independend of all other user-aggregates - therefore I don't need to replay them in chronolocial order, like User1-Event1 - User2-Event1 - User2-Event2 - User1-Event2 and so on - It's really okay to do it like this: User1-Event1 - User1-Event2 and then User2-Event1 - User2-Event2 - it's only important to keep the event order per stream - not between streams.

For the relations now: After I replayed all users, I can safely replay all friendship relations - it could happen, that a user is not existent anymore in the readmodel (because there was a deleted-event) - the projection needs to handle this case and reject the made-friend-with event in this case.

Note: This is also the way how replaying stream-projections in Greg's EventStore works - I tested this myself and it works without problems.

Last point:
The reason why I suggested event-store-bus-bridge (It doesn't has to be!):
When replaying you really don't want to have the streams at hand but push those events to the projections - so having the event-bus at hand in conjunction with the event-store really make sense to me.

**Comment by codeliner** [comment]
@prolic thx for detailing your idea. Makes a lot of sense to me now.

But what options do I have if chronological order is important (at least the one we can offer by ordering createdAt by microseconds)?

I'd need the new stream-to-stream projections, right?

**Comment by prolic** [comment]
Stream-to-Stream projection would only be useful for this, when they are enabled before the first event ever is recorded and the projected was never reset. Otherwise the same replay method as above applies.

Can you provide a use-case where chronological order matters? I tried to give an example with relationships above where chronological order seems to be important - but as I showed it's not.

**Comment by codeliner** [comment]
You have a simple version in your use case:
> - the projection needs to handle this case and reject the made-friend-with event in this case.

User-Deleted scenario is easy to handle in the projection but what about more complex use cases? 
Anyway, I agree that we can move this task to userland projections. We just need to point it out in the docs.
