### ISSUE TITLE
RFC some constraints on metadata and event stream names

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#191]
I want to propose some changes here:

1) Move aggregate_type and aggregate_id to event metadata. This is really only needed in special case that one stream per aggregate is not used. With that change we can have a unified event stream structure independent of which stream strategy is used.

2) All internal metadata should be prefixed - I propose the underscore `_` for this. This means all internal metadata (currently this would be: causation_id, causation_name, aggregate_type and aggregate_id) will be prefixed with underscore. Userland metadata is forbidden to use the underscore as first character of their metadata as it's reserved for internal usage. I don't know yet if an exception is necessary or if a note in the docs to strongly discourage it is enough.

3) All internal streams like for stream-projections and so on (see: https://github.com/prooph/event-store/issues/193) will be prefixed with an underscore `_`, too. All userland streams are required not be begin with underscore as this is reserved for internal useage. Again: I don't know yet if an exception is necessary or if a note in the docs to strongly discourage it is enough.

**Comment by codeliner** [comment]
I'd go for the note in the docs, otherwise we would need to check each metadata key. People should be familiar with conventions because frameworks use this a lot to make things easier.

I like the idea but we need to provide migration paths. Upgrading to the new major versions will be work and people need to be aware of that.

**Comment by prolic** [comment]
I am thinking of providing a migration script for the database using the event store api, so it should work for all adapters without providing special migration scripts for every database vendor.

**Comment by sandrokeil** [comment]
Sounds really good and make also things easier for new people, because of less necessary fields.
