### ISSUE TITLE
RFC query-stream-api

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#192]
basicially something like this:

```
fromStream - Returns one stream to query, f.e. fromStream('user')
fromStreams - Returns a list of streams, f.e. fromStreams(['user', 'todo'])
fromCategory - Returns a list of streams in a category, f.e. fromCategory('user')
fromAll - Returns a list of all streams
whenAny($callback) - for any event do....
when('UserCreated', $callback) - for event UserWasCreated do...
foreachStream() - handle all streams in parallel (amqp or pthreads maybe)?
```

The exact implementation details are not yet subject to this RFC and need to be discusses further.

**Comment by codeliner** [comment]
sounds great, but maybe 7.1? We need to consider a lot of things and work out an API. It is a new feature and should not introduce BC breaks so we could focus on 7.0 first and add query-api in a second step?

**Comment by prolic** [comment]
Currently I think about adding this to the adapter interface, so every adapter has to support this. If we do it later, then all adapters need to add methods to the interface, so BC and next major.
Therefore I like to add it now.

**Comment by prolic** [comment]
see https://github.com/prooph/event-store/pull/213
