### ISSUE TITLE
RFC event-store HTTP API

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#194]
An HTTP API for the event-store would be a great addition (read & write to event streams).

**Comment by lucascourot** [comment]
Tell me if you need me to help you on this one

**Comment by prolic** [comment]
I added first implementation step here: https://github.com/prooph/event-store-http-api

(only quick and dirty, no tests, no reviews yet, just some simple stuff)

**Comment by codeliner** [comment]
> I added first implementation step here

and I added the first RFC for it ;) 
https://github.com/prooph/event-store-http-api/issues/1
