### ISSUE TITLE
RFC sha1 on stream names

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#196]
There are quite some restrictions on stream names and those restrictions are changing between different event-store-adapters, like f.e. forbidden characters in mysql vs forbidden characters in mongodb). Also the given maximum string length for a collection name in mongodb or a mysql-table name are a problem.

Therefore I like to propose to sha1 all stream names and create a table / collection where a mapping from hash to real stream name is put (so you can see what actual stream name are availalble).

**Comment by codeliner** [comment]
a bit more work when working directly on database level (via mongo shell f.e.) but reasoning is valid so :+1:

**Comment by oqq** [comment]
I would prefer to provide an service interface for slugify a stream name.
The default implementation could be to replace all non word characters or similar to current implementation in event store adapters.

Users could be interested to find stream tables with readable names instead of hashed ones.

**Comment by prolic** [comment]
It's based on a strategy, see: https://github.com/prooph/event-store-pdo-adapter/blob/master/src/TableNameGeneratorStrategy.php
