### ISSUE TITLE
RFC stream metadata

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#197]
Proposal is to add metadata not only to the event on a stream but also on the stream itself. Again like proposed in https://github.com/prooph/event-store/issues/191 the metadata prefixed with underscore `_` is reserved for internal usage.

This can be useful to add ACL rules to the stream itself f.e. - who is allowed to read, who is allowed to write - especially useful when we want to add an event-store HTTP API, see: https://github.com/prooph/event-store/issues/194

**Comment by codeliner** [comment]
sounds very good
