### ISSUE TITLE
RFC load max events and direction

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#198]
The current interface is:

`public function load(StreamName $streamName, int $minVersion = null): Stream`

I want to change to:

`public function load(StreamName $streamName, int $minVersion = null, int $maxVersion = null, bool $forward = true): Stream`

to allow loading events in a given range only (useful for http api f.e., see: https://github.com/prooph/event-store/issues/194) and additionally you can load the events in reverse order.

Similar to this `loadEvents` needs to be updated, too.

**Comment by basz** [comment]
What I find confusing....
Start with a min of 10. I want my set 10 not to be bigger then 10 events. Should max be 20 or 19? Do both numbers include themselves or only one of them does?

I argue the later and as such the variablenames can express that clearerly:

fromVersion, upToVersion

**Comment by prolic** [comment]
:+1: for fromVersion, upToVersion

**Comment by prolic** [comment]
Another thing to consider:
`version` is a term useful for event sourcing. The EventStore is capable of storing all kinds of event streams, also non-event-sourced. Thefore I like to suggest to rename `version` to `no` in the event stream. The `version` for event sourcing can be equal the `no` in the stream for one stream per aggregate usage, otherwise the `version` should be part of the metadata.

**Comment by prolic** [comment]
Also: shouldn't we count the events from `0` instead from `1`?

**Comment by basz** [comment]
instead of 'no' `ordinality`? (http://www.thefreedictionary.com/Ordinality)

a zero based index does not fly here. A 0'th event doesn't makes sense, only a 1st, 2nd, etc.

**Comment by codeliner** [comment]
if we rename from `version` to `no` we need a migration path!

**Comment by codeliner** [comment]
except the rename i like the RFC a lot :+1:

**Comment by oqq** [comment]
How about to request an amount of events?
fromVersion, amountOfEvents

**Comment by prolic** [comment]
@oqq my explanation in code:

```
$minVersion = 12;
$amountOfEvents = 100;
$maxVersion = $minVersion + $amountOfEvents;
```

easy?

**Comment by oqq** [comment]
Of course!
But the question is, which version is way to go to simplify the api.

e.g. using a paginator you would simple call "give me the next 10 elements" instead of give me all elements from x to x+=10.

minVersion and maxVersion has to be calculated, instead of only minVersion.

**Comment by prolic** [comment]
@oqq

Agree!
Let's change this to:

public function load(StreamName $streamName, int $fromNumber = null, int count = null, bool $forward = true): Stream

I will update the PR.

**Comment by oqq** [comment]
$forward could omitted if the $count var could be negative.
But thats a big possibility to confusing, so i am not realy sure about that. ;)

**Comment by prolic** [comment]
Referring to Greg's EventStore let's keep it. Here we have this:

`curl -i http://127.0.0.1:2113/streams/newstream/2/forward/1` (load from event 2 forward 1 event)

`curl -i http://127.0.0.1:2113/streams/newstream/head/backward/5` (load from last event backward 5 events)

**Comment by oqq** [comment]
Oh that is nice and very readable. 👍 
But maybe it would be better to split booth in separate methods.
e.g. ```load()``` and ```loadReverse()```

Each concern a method, how DDD Borat would says. ;)

**Comment by prolic** [comment]
Grrrrrrr... okay :+1:

**Comment by prolic** [comment]
Migration of existing streams is planned anyway on my side :-)
See my other RFC's.

Am 25.10.2016 16:55 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by prolic** [comment]
Why not? The stream starts at position zero. The same as an array index
starts with zero.

Am 25.10.2016 16:52 schrieb "Bas Kamer" <notifications@github.com>:
>
> instead of 'no' ordinality? (http://www.thefreedictionary.com/Ordinality)
>
> a zero based index does not fly here. A 0'th event doesn't makes sense,
only a 1st, 2nd, etc.

**Comment by prolic** [comment]
An event in a stream has a position in that stream. Not a version.
We speak of event streams here, not event sourcing.

Am 25.10.2016 16:57 schrieb "Sascha-Oliver Prolic" <
saschaprolic@googlemail.com>:
