### ISSUE TITLE
Promote LTS for current major version

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store#199]
Due to massive changes that come along with the next major release I'd suggest we provide long term support for 2 years for the current versions and note that in the docs so that people have time to upgrade.

**Comment by prolic** [comment]
The event-store v6 series is compatible with PHP 7 and PHP 7 active support end 3 Dec 2017. So one year LTS support is enough I think.

**Comment by codeliner** [comment]
agreed

**Comment by sandrokeil** [comment]
Yes, we should use the PHP lifecycle. :+1:

**Comment by prolic** [comment]
Where to put this notification? New website?

**Comment by codeliner** [comment]
New Website is a good place

**Comment by codeliner** [comment]
Just saw the [Version Guidance](https://github.com/guzzle/guzzle#version-guidance) for guzzle and thought that would be a good idea for our prooph packages, too
