### ISSUE TITLE
How works MetadataMatcher with array values?

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store#209]
I'm not sure how the [MetadataMatcher](https://github.com/prooph/event-store/blob/develop/src/Metadata/MetadataMatcher.php) works with array values. The equal check works fine, but what is with the [other checks](https://github.com/prooph/event-store/blob/develop/src/Adapter/InMemoryAdapter.php#L217)? We have also no tests for this case I guess.

**Comment by prolic** [comment]
Do you want to compare ['foo' => 'bar'] < ['foo' => 'baz'] ?

I'm not sure I get your question.

**Comment by sandrokeil** [comment]
Yes, something like this or how is this call `withMetadataMatch('foo', $LessThanOperator, ['bar' => 'baz'])` handled?

**Comment by prolic** [comment]
```
php > var_dump(['f' => 2] < ['f'=> 3]);
bool(true)
php > var_dump(['f' => 2] > ['f'=> 3]);
bool(false)
```

so what's the problem?

**Comment by prolic** [comment]
We could add however support for deeper queries like this:

json:
```
{
    'foo': {
        'bar': 'baz'
    }
}
```

Didn't test it yet, but I think you could not query where 'foo.bar' = 'baz', this had to be added.

**Comment by sandrokeil** [comment]
Interesting that this works, seems like an [undocumented feature](http://php.net/manual/en/language.operators.array.php).

**Comment by prolic** [comment]
we can also throw an exception in this case, might not work with nested array, didn't test it.

**Comment by prolic** [comment]
This is not a problem at all. The metadata can only be scalar values and not an array, see: https://github.com/prooph/common/blob/develop/src/Messaging/MessageDataAssertion.php#L87
