### ISSUE TITLE
RFC problem with TransactionalEventStore and ArangoDB

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store#221]
I see some problems with `TransactionalEventStore` interface and ArangoDB or other event store implementations who handles transactions in another way. ArangoDB has no `beginTransaction`, `commit`, `rollback` or `isInTransaction` see [docs](https://docs.arangodb.com/3.1/Manual/Transactions/TransactionInvocation.html).

Can we achieve more interoperability by simply using a function e.g. `executeTransaction` which gets a list of streams? But we have to differ between `create` and `appendTo`. Maybe instead of using `create` and `appendTo` methods, we introduce a stream type which can be `create` or `appendTo`, so the provided stream list can be executed in order.

/cc @prolic @codeliner

**Comment by codeliner** [comment]
Can't we handle the logic behind the `TransactionalEventStore` interface?
ArangoDB handles transactions in one go but IMHO this is implementation detail. From a user POV it makes no difference:

```php
$arangoDbES->beginTransaction();
//$this->inTransaction = true;
$arangoDbES->create($stream);
//$this->transactionOperations[] = new ArangoCreateStreamOperation($stream);
$arangoDbES->appendTo($streamName, $streamEvents);
//$this->transactionOperations[] = new ArangoAppendToStreamOperation($streamName, $streamEvents);
$arangoDbES->commit();
//$this->executeTransaction();
//foreach($this->transactionOperations as $op) {/*map to transaction description*/}
//$this->arangoConnection->transaction($transactionDescription); 

//or in case of a userland error before $arangoDbES->commit() is called
try {
//do something that causes an error
} catch (\Throwable $error) {
  if ($arangoDbES->isInTransaction()) { //return $this->inTransaction;
    $arangoDbES->rollback();
    //$this->transactionOperations = [];
    //$this->inTransaction = false;
  }
}
```

**Comment by sandrokeil** [comment]
Yes that should be possible. It's only confusing if you have to use these methods and read in the ArangoDB docs, transaction is handled in one go.

**Comment by prolic** [comment]
@sandrokeil can we close this now?
