### ISSUE TITLE
Outsource AggregateTranslator configuration

### ISSUE THREAD

**Issue by dropdevcoding** [prooph/event-store#237]
While reading #235 and therefore looking at ```ConfigurableAggregateTranslator``` I realized that there might be the possibility to optimize the configuration possibilities of ```ConfigurableAggregateTranslator``` regarding separation of concerns. What do you think of using a dedicated ```AggregateTranslatorConfiguration``` object which holds and handles all the stuff currently done in the translator itself. By providing a factory method for defaults (```AggregateTranslatorConfiguration::createWithDefaults()```) and hiding the constructor you could ensure consistency. The configuration itself should be immutable providing functions like ```withVersionMethodName```. 

The ```ConfigurableAggregateTranslator``` may then have a constructor like ```__construct(AggregateTranslatorConfiguration $configuration = null)``` which will be initialized with the default factory method mentioned above when no config is provided.

If you find this useful / helpful, I may provide a PR that I already prepared (some test cases for checking immutability and comments are missing right now).

**Comment by codeliner** [comment]
tbh I'm not fully convinced. I agree that it would look nicer with a `AggregateTranslatorConfiguration` but it also introduces a new class without much benefit. The `ConfigurableAggregateTranslator` is already a small class with a single purpose (connect prooph repository with individual aggregate implementation). 

If you want to use your own event-sourcing implementation instead of [prooph/event-sourcing](https://github.com/prooph/event-sourcing) you can extend the `ConfigurableAggregateTranslator` (note: it is not marked as final) and override the constructor:

```php
class MyAggregateTranslator extends ConfigurableAggregateTranslator
{
  public function __construct()
  {
    parent::__construct(/* pass custom method names here */);
  }
}
```

Then you can inject `MyAggregateTranslator` into a prooph repository and you're done.
But please submit your PR (even if it is work in progress) and we can discuss it. Maybe it looks much better than current implementation ;)

**Comment by dropdevcoding** [comment]
Created #238 

I agree that it doesn't add that much benefit at first look but if you look at the unit tests it feels much cleaner to configure it via:

```php
$config = AggregateTranslatorConfiguration::createWithDefaults();
$config = $config->withMessageToEventCallback(function (Message $message) {
   // return event
});
$translator = new ConfigurableAggregateTranslator($config);
```

than

```php
$translator = new ConfigurableAggregateTranslator(null, null, null, null, null, null, function (Message $message) {
    // return event
});
```

Also the unit tests are more readable and focus on the separate concerns.

Thoughts and comments appreciated :-)

**Comment by codeliner** [comment]
> but if you look at the unit tests it feels much cleaner 

definitely agree here, but we need to keep some things in mind:

First: You do this configuration once based on your naming preferences for all your aggregates. After that you never touch this piece of code again, except you want to refactor your entire domain.
Second: prooph is a library we need to take performance considerations into account. A nice and clean codebase is good, but on the other hand it is also more work for PHP (more method calls) for every request. In a critical part of prooph I'd always go the immutable object and clean code route (see prooph's message implementation) but applying this pattern everywhere would slow down prooph as a whole.

> Furthermore your inheritance proposal wouldn't adhere to O/C principle and would add extra complexity

extra complexity -> Agreed, but I can live with it :P
O/C principle -> why not? You can extend the class and override the constructor but you cannot access/set the properties directly. Looks like O/C to me.

**Comment by shochdoerfer** [comment]
I might be biased but I like the idea of having a separate configuration class. That's the route I took for [Disco](https://github.com/bitexpert/disco) and I begin like it especially when you have a lot of optional parameters. Keeping that handling separate from the instance using the configuration feels like a win to me ;)

**Comment by dropdevcoding** [comment]
Well yes, it would afford an extra call to the configuration's getters but do you really think this might potentially be a performance issue? Since the methods are simple getters I doubt that this would be the case (possibly we could loadtest both variants to see).

Regarding the O/C principle you're right from this perspective but nevertheless I then would prefer using the bloated constructor instead of inheritance.

**Comment by codeliner** [comment]
regarding performance: not an issue when only looking at this small piece of code but it is a performance drawback when applied everywhere in the system. IMHO it is a good idea to keep bootstrap logic lean when you want to have lightning fast PHP services, So yes, I try to keep the less important parts of a system lean and apply clean code (that requires more work for PHP) only to critical parts of the system like the domain model or communication objects like the prooph messages. 
But that is only my personal preference, we can change it. Let's see what @prolic thinks about it.

**Comment by sandrokeil** [comment]
Why not mix the stuff together? Something like this.

```php
    public function __construct(AggregateTranslatorConfiguration $configuration = null)
         $configuration = $configuration ?: AggregateTranslatorConfiguration::createWithDefaults();
         $this->identifierMethodName = $configuration->identifierMethodName();
        // ...
    }
```

**Comment by dropdevcoding** [comment]
Just the before I read the notification mail exactly this suggestion lept into my mind. Though this solution is kind of redundand since the values are held twice, it would be a good compromise solution.
