### ISSUE TITLE
Problem with ActionEventEmitterEventStore and Projections

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#240]
Currently it delegates the projection creation to the used event store implementation. This is a problem, as the wrapped event store is then not used in the projection itself, and you cannot attach listeners to it during projection's `emit` and `linkTo`.

`$eventStore->createProjection($eventStore)` would solve the issue (adding event store as optional parameter, which will only be set by action event emitter event store) - but this looks weird and might lead to some people injecting a complete different event store instance, which would be cleary wrong.

Ideas?

@codeliner @oqq @bweston92

**Comment by bweston92** [comment]
I'm not to sure I get the problem. `$eventStore->createProjection($eventStore)` could the `createProjection` not just pass `$this` ?

**Comment by prolic** [comment]
@bweston92 that's excatly the problem, that `$this` is passed.

see: https://github.com/prooph/event-store/blob/develop/src/ActionEventEmitterEventStore.php#L314 and https://github.com/prooph/event-store/blob/develop/src/InMemoryEventStore.php#L291-L303.

This way `$actionEventEmitterEventStore->createProjection(...)` will use `InMemoryEventStore` within the projection, not the `ActionEventEmitterEventStore`.

**Comment by codeliner** [comment]
tbh I've no idea :( thought about decoration or reflection but both is not an option here. 
`$eventStore->createProjection($eventStore)` would be the only solution but it looks strange.

Question: Do we really need these projection factory methods in the event store interface? Why not set up projections with normal factories? This way it would also be possible to mix PostrgresEventStore with mongoDB projection?

**Comment by prolic** [comment]
In pdo-event-store I reuse the pdo connection, event stream table, and some other information, that is stored in private properties of the mysql/postgres-eventstore in the projection constructor. This way it's very easy to set up.

Using a distinct factory might be a solution however, that would not be that ugly. I will try to update this when I work on the pdo-event-store again and update it (remove abstract classes, as well). Latest should be this weekend.

**Comment by prolic** [comment]
Oh maybe something like this in event-store interface:

`public function getProjectionFactory(): ProjectionFactory` ?

This way this can be used by the action event emitter event-store.

Pro:

- clean solution

Con:

- it bloats the interface a little - but I think we can live with that.

Another possibility:

We don't add it to the interface, and the event store implementation simply uses it's hard-coded known factory. For the action event emitter, we inject that factory in the constructor.

Pro:

- no bloated interface, clean solution

Con:

- you have more configuration to do for the action event emitter event store - give him the factory classes in the config

**Comment by codeliner** [comment]
not bad!

I think my favorite is the first option: `public function getProjectionFactory(): ProjectionFactory`

**Comment by prolic** [comment]
one factory for all 3 (query, projection, readmodelprojection)? or one by one? this would mean adding 1-3 more methods to the interface.

**Comment by prolic** [comment]
having slightly more complex action event emitter event store config would make the interface more cleaned up.

**Comment by prolic** [comment]
@oqq @shochdoerfer @sandrokeil @bweston92 @basz your thoughts?

**Comment by sandrokeil** [comment]
> Question: Do we really need these projection factory methods in the event store interface? Why not set up projections with normal factories? This way it would also be possible to mix PostrgresEventStore with mongoDB projection?

I think it's really important to mix an event store with an other projection store. Using a method `getProjectionFactory()` in the interface itself introduces new problems.

> one factory for all 3 (query, projection, readmodelprojection)? or one by one? this would mean adding 1-3 more methods to the interface.

Can we use a *default* factory and put it to the `\Prooph\EventStore\Projection\ProjectionOptions` class. So it's optional configurable but works out of the box?

**Comment by shochdoerfer** [comment]
I think I would go the distinct factory route.

**Comment by bweston92** [comment]
I don't think this should be coupled in the interface for the event store at all.
It may mean more configuration and more verbose setup how ever it will keep it cleaner.
I agree with @sandrokeil on a default factory that is configurable and optional.

**Comment by prolic** [comment]
see: https://github.com/prooph/event-store/commit/8c2c8c19ddb9d98d28b901cabbe97f726ad720e2

**Comment by oqq** [comment]
As first step we should implement a `EventStoreDecorator` Interface with a `getInnerEventStore()` method to get rid of reflections. Also instead of reflections i would prefer a `getKnownStreamNames()` method in `EventStore` interface. Maybe `getKnownStreamNames()` is enough, since the `ActionEventEmitterEventStore` could also provide the streamNames from the inner `EventStore`.

**Comment by oqq** [comment]
Is there a reason why the Projections could get handle the `EventEmitterEventStore`? Why they need the inner EventStore?

**Comment by prolic** [comment]
An `EventStoreDecorator` is not needed. To get the list of known streams you need to access the underlying database. In `InMemoryEventStore` this is not possible, therefore only there reflection is used. This is not the case in real-world-implementations (like pdo-event-store).

I removed the getKnownStreamNames() method to reduce methods calls, as this happens only once in the constructor.

About the second question, see: https://github.com/prooph/event-store/blob/remove_abstract_classes_in_projections/src/ActionEventEmitterEventStore.php#L360-L366

The correct event store (outer one) is used.

**Comment by prolic** [comment]
Btw:

I checked again about mixing PostgresEventStore with MongoDbProjection. With the shipped classes, this will NOT be possible. The projection class needs to access the underlying database, and MongoDbProjection cannot know about the structure in Postgres / MySQL. Also I don't want to add additional methods to expose inner workings to the outside, so this is a good way.

If you really need this for whatever reasons, you have to create your own Projection-Implementation, that can do this.

The constructor currently allows `EventStore` interface - I should maybe enforce a stricter check.

**Comment by prolic** [comment]
I checked the constructor already, there are already checks in place!

**Comment by codeliner** [comment]
I'm just thinking loud now:

The advantage of **ReadModel**Projections are, that you can use one database system for your write model but another for your read model so you are free to pick the right tool for the job. That is the reason why it would be nice to mix database systems. I think this is not limited to ReadModelProjections but is true for StreamProjections, too. 
Would it be possible to use a PostgresEventStoreQuery insight a MongoDbProjection?
Query comes in, projection goes out?

**Comment by codeliner** [comment]
Ah sorry, the naming confused me. The injected ReadModel persists itself, right? Maybe it is better to rename `ReadModelProjection` -> `ReadModelProjector`?
So mixing database systems is possible. You just need to inject a MongoDbReadModel, right @prolic ?

**Comment by prolic** [comment]
Exactly, you can inject a MongoDbReadModel into a PostgresReadModelProjection. The used ReadModel instance has to follow the interface (for convenience there is also an abstract class, where you can extend from). The read model can use it's own db-connection and use whatever backend. You are simply not allowed to use a MongoDbReadModelProjection together with MySqlEventStore, unless you provide a custom ReadModelProjection implementation.

About the naming: I would stick to ReadModelProjection (same as Projection) - not Projector.

**Comment by codeliner** [comment]
#239 was merged. 
However, if anyone has a brillant idea how we can solve the problem without adding new classes to the event store interface, I'd be happy to discuss it! Thought about it myself while reviewing #239 again, but I have no better idea.

**Comment by sandrokeil** [comment]
One more question, why we don't use a projection factory with container interop like always? Because we have a name and options. I don't see a reason e.g. for the InMemoryEventStore to use methods instead of container-interop factories.

For me it looks complicated and weird to have factory methods in the event store. But I know some people don't like config driven development. However, I think it's much bloated with these methods.

```
public function createQuery(QueryFactory $factory = null): Query
    {
        if (null === $factory) {
            $factory = $this->getDefaultQueryFactory();
        }

        return $factory->factory();
    }

    public function createProjection(
        string $name,
        ProjectionOptions $options = null,
        ProjectionFactory $factory = null
    ): Projection {
        if (null === $factory) {
            $factory = $this->getDefaultProjectionFactory();
        }

        return $factory->factory($name, $options);
    }

    public function createReadModelProjection(
        string $name,
        ReadModel $readModel,
        ProjectionOptions $options = null,
        ReadModelProjectionFactory $factory = null
    ): ReadModelProjection {
        if (null === $factory) {
            $factory = $this->getDefaultReadModelProjectionFactory();
        }

        return $factory->factory($name, $readModel, $options);
    }

    public function getDefaultQueryFactory(): QueryFactory
    {
        return new InMemoryEventStoreQueryFactory($this);
    }

    public function getDefaultProjectionFactory(): ProjectionFactory
    {
        return new InMemoryEventStoreProjectionFactory($this);
    }

    public function getDefaultReadModelProjectionFactory(): ReadModelProjectionFactory
    {
        return new InMemoryEventStoreReadModelProjectionFactory($this);
    }
```

I will take a deeper look later, maybe I miss something here.

**Comment by prolic** [comment]
@sandrokeil the reason is, that you should be only able to configure a projection / query with the correct event store instance. while you can still instantiate the projection / query manually, you can still run in this issue, but it's unlikely someone does that.
a false configuration can lead to injecting the wrong event store instance to the projection / query and make it useless.
