### ISSUE TITLE
Read-only event store interface

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store#250]
Idea from the chat:

redis would still be very interesting if it supports auto increment because one could use redis event store as a super fast read slave

a projection could copy all events from postgres master to redis in memory slave and other projections read from there

**Maybe we should prepare for that an add read only event store interface?**

**Comment by oqq** [comment]
Could be done with https://redis.io/commands/incr.

The way to go would always be a Lua script to execute all operations. Redis guarantees atomicity for Lua scripts. Thats also the reason i am still believe a full redis-event-store could be done.

+1 for read only interface.

**Comment by codeliner** [comment]
@oqq How can you pass the events to the lua script? json_encode them and invoke the Lua script with exec() ?

**Comment by oqq** [comment]
Maybe you throw your eyes on the current implementation. I have already used Lua scripts for that:

The script execution: https://github.com/prooph/event-store-redis-adapter/blob/6d26eea9cf4adb50fbf5a6d992578db16e184a16/src/PredisEventStoreAdapter.php#L219

The Lua script:
https://github.com/prooph/event-store-redis-adapter/blob/6d26eea9cf4adb50fbf5a6d992578db16e184a16/src/RedisCommand/InsertEvent.php#L25

Only challenge here is to create a Lua script which produce index contents like the current implementation by only using a key/value store. Storage is fine, but projections should also be performant.

Maybe I should start with experimental repo how you have done with mongodb event store. 🐎

**Comment by codeliner** [comment]
ah nice, thanks for the hints

> Maybe I should start with experimental repo how you have done with mongodb event store. 

that would be great. @sandrokeil is doing the same with ArangoDb.

**Comment by codeliner** [comment]
@oqq ReadOnlyEventStore available now
