### ISSUE TITLE
Add support for inline upcasting

### ISSUE THREAD

**Issue by mrook** [prooph/event-store#254]
Upcasters are classes that take one input event of revision `x` and output zero or more new events of revision `x + 1`.

They should be executed inline when loading event streams from the event store. Upcasters can possibly be implemented as event store plugins.

Possible scenarios:

- single event to single event
- single event to multiple (or zero) events
- chaining multiple upcasters

Inspiration: http://www.axonframework.org/docs/2.0/repositories-and-event-stores.html#event-upcasting (and https://docs.axonframework.org/v/3.0/part3/repositories-and-event-stores.html for the new version).

**Comment by codeliner** [comment]
Sounds interesting, thx

**Comment by prolic** [comment]
@mrook see https://github.com/prooph/event-store/pull/255
