### ISSUE TITLE
Remove PHP_INT_MAX constant

### ISSUE THREAD

**Issue by oqq** [prooph/event-store#271]
I would prefer to using `null` instead of `PHP_INT_MAX` in `load` methods and let decide the implementation how to handle this value. In most cases this value could be ignored in query if it is `null`, if it is not necessary for index usage. Also, `PHP_INT_MAX` has a higher memory footprint than `null`. Even it is not always true that PHP and the underlying storage uses the same cpu architecture. (32bit vs. 64bit)

I have not investigate much in that issue. Maybe there is a good reason for `PHP_INT_MAX` instead of `null`. But if not, please let us remove that constant. I always feel bad if I have to use this constant with event_store.

**Comment by prolic** [comment]
What about loadReverse then?

**Comment by oqq** [comment]
The EventStore implementation has to know how to handle `null`. e.g the PdoEventStore removes the `no`from the where clause **OR** implement PHP_INT_MAX again. Its up the the event store implementation. 

With PHP_INT_MAX I am not able to get if a user says "no limit" or "a big number to start".
