### ISSUE TITLE
Rename projection to projector

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#273]
A projector creates a projection, right? We should think about renaming the classes where applicable.

Thoughts?

@codeliner @oqq @basz

**Comment by basz** [comment]
I agree; The result of a projector would be a projection

If you take this further a ReadModel could also be called a Projection...

**Comment by prolic** [comment]
@basz I think this could let to confusion, if you need to inject a projection into a projector in order to create a projection. Inject a read model implementation into a projector to create a projection sounds way better to me.

**Comment by prolic** [comment]
A pull-request is created, so we can discuss changes also there and see what it looks like.
