### ISSUE TITLE
Trackable transaction in TransactionalActionEventEmitterEventStore

### ISSUE THREAD

**Issue by lunetics** [prooph/event-store#283]
My Idea:

Since one request "could" handle multiple commands (which will be wrapped in a transaction), it could beneficial to track each distinct "transactionl" action.

Don't know what would be the best place to do such a thing. Would it be possible in the TransactionalActionEventEmitterEventStore at all? Or do we need the TransactionManager from the EvenStoreBusBridge (not too fond of)

For now i build some "poor mans" count, but i would rather rely on a "true" transactional id given from the event store
```php
   public function attachToEventStore(ActionEventEmitterEventStore $eventStore): void
    {

        // Track transactions
        if ($eventStore instanceof TransactionalActionEventEmitterEventStore) {

            $eventStore->attach(TransactionalActionEventEmitterEventStore::EVENT_BEGIN_TRANSACTION, function (ActionEvent $event) {
                static $transactionInstance = 0;
                $transactionInstance++;

                $time = $this->stopwatch->start('event_store.transaction_'.$transactionInstance, 'section');
                $this->eventStoreActions[] = new DebugEvent($event, $time);
            }, 1000);

            foreach ([TransactionalActionEventEmitterEventStore::EVENT_COMMIT, TransactionalActionEventEmitterEventStore::EVENT_ROLLBACK] as $eventStoreEvent) {
                $eventStore->attach($eventStoreEvent, function (ActionEvent $event) {
                    static $transactionInstance = 0;
                    $transactionInstance++;
                    $time = $this->stopwatch->stop('event_store.transaction_'.$transactionInstance);
                    $this->eventStoreActions[] = new DebugEvent($event, $time);
                }, -1000);
            }
        }
    }
```

**Comment by prolic** [comment]
I'd prefer class properties instead of static $transactionInstance = 0;

**Comment by prolic** [comment]
copied from chat:

> @codeliner
> @lunetics nice work! Regarding transaction: we don't need a transaction uuid because we have the causation id -> command uuid. One command = one transaction. We have this CausationMetadataEnricher https://github.com/prooph/event-store-bus-bridge/blob/master/src/CausationMetadataEnricher.php
If it is activated you have the reference in each event

**Comment by lunetics** [comment]
@prolic @codeliner unfortunately the begin / commit / rollback events don't carry such information

**Comment by codeliner** [comment]
@lunetics sorry, `causation_id` is assigned to each domain event, not the action event of the event store. See the source code of linked CausationMetadaEnricher
