### ISSUE TITLE
Flag / Method to turn off transaction handling ?

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store#292]
From the chat:
 
@max-voloshin
> It would be nice transaction behavior was separated from event store into decorator level for example
> It would make prooph event store more flexible and friendly to different environments

Maybe we can add a method like `$eventStore->disableTransactionHandling()` to hand over transaction handling of the underlying db connection to the user.

If transaction handling is disabled the event store would not check for an active transaction nor would it start, commit or roll back one.

Thoughts? @prolic @basz @oqq ?

**Comment by prolic** [comment]
I am against this, as it would break current behaviour of non-transactional event stores. F.e. MySqlEventStore: it has no transaction support, however a single call to appendTo or create is tranasctional, when giving transaction control over to the user, it will no longer be and cannot be ensured anymore.

**Comment by codeliner** [comment]
> when giving transaction control over to the user, it will no longer be and cannot be ensured anymore.

Yeah but this is no longer our problem then. I'm talking about a feature that needs to be enabled.

It can be very useful in an application where you want to migrate to event sourcing or just want to record domain events along with your normal state changes.

Let's say you use Doctrine and your entities can also record domain events.
The entity repository now wants to persist state change in the entity (graph) using Doctrine's EntityManager and ORM magic and **in the same transaction** the repository wants to use prooph/event-store to add the domain events to a stream.

Not the fastest solution but for low or medium traffic applications (a lot of enterprise apps are only low traffic) absolutely no problem. 

And a user could also MySql turn back into a transactional event store if they use SingleStreamStrategy where they have to create the event streams(s) upfront anyway.

**Comment by max-voloshin** [comment]
@codeliner, you described exactly my intention 👍

**Comment by prolic** [comment]
I see ... I will check the existing code the next days.

**Comment by prolic** [comment]
Question to this:

We could do this by adding a parameter `bool $disableTransactionHandling = false` to all pdo-event-store implementations. Would that be enough for ya? This way we don't need to provide any additional interfaces.

**Comment by codeliner** [comment]
I think that would be enough

**Comment by max-voloshin** [comment]
> We could do this by adding a parameter bool $disableTransactionHandling = false to all pdo-event-store implementations.

Do you mean `__construct` parameter? Yeah, it would be enough.

Can it also be done in `\Prooph\SnapshotStore\Pdo\PdoSnapshotStore::__construct` for the same reasons? Sorry for the non-relevant to `event-store` question, but I think it 'd be good for prooph components to be consistent.

**Comment by max-voloshin** [comment]
@codeliner @prolic this issue can be closed, thank you!
