### ISSUE TITLE
Documentation out of sync

### ISSUE THREAD

**Issue by camuthig** [prooph/event-store#300]
I think the docs at http://getprooph.org/docs/html/event-store/intro.html might be out of sync with the latest release of this project. The readme doesn't include the Doctrine persistence adapter but the docs still show it.

**Comment by prolic** [comment]
@camuthig This is already done here: https://github.com/prooph/event-store/blob/master/README.md. The documentation will be recreated the next few days.

/cc @codeliner

**Comment by codeliner** [comment]
yeah sorry, the docs are out of date but will be updated soon. Stay tuned

**Comment by codeliner** [comment]
Docs are up-to-date now
