### ISSUE TITLE
Metadata Aggregate ID can be an integer and causes errors (v6)

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store#314]
The identity map causes errors if [aggregate id is a numeric string](http://sandbox.onlinephpfunctions.com/code/579a273a1e1425faeffa9ea0d484a6629992dfa5).

> Strings containing valid decimal integers, unless the number is preceded by a + sign, will be cast to the integer type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.

An explicit string type cast is needed [here](https://github.com/prooph/event-store/blob/6.x/src/Aggregate/AggregateRepository.php#L272).

```php
$domainEvent = $domainEvent->withAddedMetadata('aggregate_id', (string)$aggregateId);
```
@prolic The PR will be for version `v6` and against this repository (v6 branch). We have to check if this can also happen with the new event store implemenation.

**Comment by prolic** [comment]
yep, you're right. in v7 we have scalar type hints and strict types enabled, so this shouldn't be an issue there. will you provide a PR incl tests?
