### ISSUE TITLE
Using MongoDB for writing projections and MariaDB as the event store

### ISSUE THREAD

**Issue by mumia** [prooph/event-store#317]
Excuse me if this is just a newbie question.

From what I gathered the configuration for the projections is limited to PDO which limits the type of databases that we can use for projections.

Is there a way, using standard configs, to use mongoDB (for example) as the write support for projections?

**Comment by prolic** [comment]
Your projections can write to any target. No matter which one it is.

**Comment by mumia** [comment]
Thanks for quick answer.

Do you know of any example of how to configure this type of setup?

P.S.: I'm using the Symfony bundle event store

**Comment by prolic** [comment]
This has nothing to do with symfony. Just implement the readmodel
interface. That's it.
