### ISSUE TITLE
Projections vs. event listners

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store#322]
We should add a section in the docs to give some advice in which cases you use a projection and wich cases you use event listeners (sync and async)

From the chat by @fritz-gerneth 

we(company) use this as a rule of thumb:
projections:

easy replayability
perform only updates on read model
do not trigger new commands
event handlers:

for one-time actions (e.g. trigger new command, send email.. )
process managers (process state usually is modeled explicitly)

**Comment by prolic** [comment]
Since noone did it, I'll close this issue now, you can still do it.
