### ISSUE TITLE
[RFC] Remove stream position from metadata

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#324]
Two options:
- either remove completely
- or find another way

This has to be evaluated.

**Comment by codeliner** [comment]
reasons?

**Comment by codeliner** [comment]
We introduced stream position because projections need to know the position.
Maybe we could rewrite `EventStore::load` and `EventStore::loadReverse` to take an event uuid instead of a position and provide newer/older events starting from that event.

**Comment by prolic** [comment]
I am not saying we should remove it completely, just remove it away from
the metadata. We also have "created_at", "event_id", and so on, which exist
but are not part of metadata.


Sascha-Oliver Prolic

2018-03-15 19:43 GMT+08:00 Alexander Miertsch <notifications@github.com>:
