### ISSUE TITLE
[RFC] Creating read model from a category with PdoEventStoreReadModelProjector in wrong order

### ISSUE THREAD

**Issue by jvdlaar** [prooph/event-store#330]
When you do something like this:
```
        $projector = $this->projectionManager
            ->createReadModelProjection('listings-admin', $this->readModel)
            ->fromCategory('listing')
            ->whenAny(function (array $state, Event $event) use ($mapper) {
                /** @var ReadModel $readModel */
                $readModel = $this->readModel();

                if ($event instanceof Added) {
                    $readModel->insert($event->aggregateId(), $mapper->map($event));
                } else {
                    $readModel->update($event->aggregateId(), $mapper->map($event));
                }
            })
        ;
```

When you replay your events, then it is replayed per stream. So first all events from stream 1, then stream 2, etc.

My streams are added in the wrong order. So I have 3 streams:

1. Dwelling
2. Sales
3. Listing

Only the Listing stream has events that does an insert, the sales / dwelling streams are for updates only. So now it first does all the updates of something that doesn't exist yet, then it does the insert.

Easiest solution for our case would be to make sure that the Listing stream is created first and then everything is grand again... but perhaps it would be nice to be able to set an order per stream in a category?

**Comment by prolic** [comment]
You can achieve ordering in the following ways:
1) Store the events in some property (or on disk) and apply them later (if event it too new and you want to apply others first)
2) use something like this: https://github.com/prooph/event-store/blob/6.x/src/Util/CompositeIterator.php - see related test-case for usage.

In the next major event-store release ordering will be implement by default.
