### ISSUE TITLE
InMemoryProjectionManager could not handle NonTransactional..EventStore

### ISSUE THREAD

**Issue by oqq** [prooph/event-store#335]
I run into an issue if is use the `NonTransactionalInMemoryEventStore`.
Since the `InMemoryProjectionManager` expects an instance of the `InMemoryEventStore`, I got an exception. Same for the `InMemoryEventStoreReadModelProjector`, `InMemoryEventStoreProjector` and other classes.

So, is this intended, while the NonTransactional is not usable for projections, or is this a bug?

For the latter one I could provide a small fix by allow also the `NonTransactionalInMemoryEventStore` in all classes, or add a new Interface for booth `EventStore`s and test only against that interface.

Affected files:
https://github.com/prooph/event-store/blob/30b5c4195895e1eef6945ea12376e2f74399c414/src/Projection/InMemoryEventStoreProjector.php#L139
https://github.com/prooph/event-store/blob/30b5c4195895e1eef6945ea12376e2f74399c414/src/Projection/InMemoryEventStoreQuery.php#L84
https://github.com/prooph/event-store/blob/30b5c4195895e1eef6945ea12376e2f74399c414/src/Projection/InMemoryEventStoreReadModelProjector.php#L155
https://github.com/prooph/event-store/blob/30b5c4195895e1eef6945ea12376e2f74399c414/src/Projection/InMemoryProjectionManager.php#L43

**Comment by prolic** [comment]
We can so allow NonTransactional. Wanna submit a pr?

**Comment by prolic** [comment]
We can also allow NonTransactional. Wanna submit a pr?
