### ISSUE TITLE
InMemoryEventStore can't read it's own events if in transaction

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store#342]
The `InMemoryEventStore` can't read it's own events if in transaction but I think it's a wrong behaviour. Normally if you are in a transaction, you can read your own stuff which was written to database in this transaction session.

It exists also a [test](https://github.com/prooph/event-store/blob/master/src/InMemoryEventStore.php#L50-L54) which checks if a stream already exists in transaction.

I will bring a PR which writes the transaction events also to `streams` property and use the `cachedStreams` only to remove certain events on roll back from `streams`.

Any concerns about this?

**Comment by codeliner** [comment]
Related PR is closed due to BC issues, so I'm closing the issue as well.
See PR for reasons: https://github.com/prooph/event-store/pull/343#issuecomment-401338835
