### ISSUE TITLE
Documentation uses wrong pcntl signal? 

### ISSUE THREAD

**Issue by Brammm** [prooph/event-store#344]
As requested by @codeliner on Gitter:

The documentation [here](http://docs.getprooph.org/event-store/projections.html) mentions that you can/should register your own signal handler in order to stop a projection correctly. It provides the following example code:

```php
pcntl_signal(SIGQUIT, function () use ($projection) {
    $projection->stop();
    echo 'Quitting...' . PHP_EOL; // added by me
});
```

When adding this code to my projection script, I would end the script with `ctrl-c` but when looking at the projections table, it would still have it's status as `running`. The `Quitting...` text would also not be printed.

Changing the example code to use `SIGINT` instead of `SIGQUIT` resulted in a properly stopped projection. The script runs on OS X, not Linux, I don't know if that matters in this case.

**Comment by prolic** [comment]
Sigint is the right signal for crtl+c. We either need to update the lib to
support both or update documentation. I thing updating lib is better. /cc
@codeliner

**Comment by Brammm** [comment]
I have to add the php.net documentation offers very little explanation on what signal is sent when.

**Comment by prolic** [comment]
I just rechecked everything again and all is good. Nothing to do here.
You won't find much about signal handlers in the php manual, and that's okay, you can get it here: http://man7.org/linux/man-pages/man7/signal.7.html

Important for you is this: `SIGINT        2       Term    Interrupt from keyboard`. So in case you want to quit from keyboard (crtl+c), then you need to use SIGINT.

**Comment by Brammm** [comment]
Thanks for the clarification, reading [this article](https://www.quora.com/What-is-the-difference-between-the-SIGINT-and-SIGTERM-signals-in-Linux-What%E2%80%99s-the-difference-between-the-SIGKILL-and-SIGSTOP-signals) it's making me think (in general when it comes to `pcntl_signal`) that you're best off adding a handler for both `SIGINT` AND `SIGQUIT` (I didn't even know about `ctrl + \`). Anyway, that's probably beyond the scope of the documentation here anyway.
