### ISSUE TITLE
InMemoryEventStoreQuery#fromStream signature does not match interface signature (Query#fromStream)

### ISSUE THREAD

**Issue by 0x13a** [prooph/event-store#362]
I am probably missing something, if so please ignore me.

I am trying to load events using a `Query` from a `SingleStreamStrategy` event store.
I am noticing that the implementations of `InMemoryEventStoreQuery#fromStream` and `PdoEventStoreQuery#fromStream` receive two parameters 

```php
public function fromStream(string $streamName, MetadataMatcher $metadataMatcher = null): Query
```

whether the interface from `Query#fromStream` has a different signature

```php
public function fromStream(string $streamName): Query
```

Is this a voluntary interface signature mismatch?
If so, are we supposed to not use a `MetadataMatcher` for loading events from a Single Stream Event Store?

Sorry again for the stupid question, I am trying to better understand the package!

**Comment by prolic** [comment]
This is intentionally. The metadata matcher was added later, but to prevent BC it was not added to the interface.
