### ISSUE TITLE
7.5.2 is completely breaking from 7.5.1

### ISSUE THREAD

**Issue by ganey** [prooph/event-store#369]
There's an awful lot of changes in 7.5.2, the file structure looks rather like the 8.x tag range.

Please remove the 7.5.2 tag

![image](https://user-images.githubusercontent.com/1401832/58084525-f701db80-7bb2-11e9-82eb-2081f1a2590f.png)

**Comment by basz** [comment]
incorrectly targeted `master`

please remove tag 7.5.2 asap

@prolic @codeliner

**Comment by prolic** [comment]
tag is deleted, creating a new one right now

**Comment by prolic** [comment]
https://github.com/prooph/event-store/releases/tag/v7.5.3

sorry!!
