### ISSUE TITLE
v7: interface mismatch Query, Projector & ReadModelProjector

### ISSUE THREAD

**Issue by basz** [prooph/event-store#373]
fromStream is defined as 

```
public function fromStream(string $streamName): Projector;
```
https://github.com/prooph/event-store/blob/7.x/src/Projection/Projector.php#L40

but implementations all use

```
public function fromStream(string $streamName, MetadataMatcher $metadataMatcher = null): Projector
```
https://github.com/prooph/event-store/blob/7.x/src/Projection/InMemoryEventStoreProjector.php#L178

**Comment by prolic** [comment]
The MetadataMatcher was added later to this function and apparently it's okay for PHP to add an additional argument to a method without touching the interface. The MetadataMatcher can be null, and so it's not a BC. For the InMemory*-implementations this change was not made. If you need that for testing purposes, you can submit a PR, but it's not a bug as it implements the interface correctly. The PDO*-implementations just provide a bit more.

**Comment by basz** [comment]
Agree on how we got here.

Two points;

- InMemory implementation *does* have the argument (see link above)
- Vimeo/psalm balks at this.

**Comment by prolic** [comment]
Yep, it's not nice, but works without BC and a good reason why not to add
psalm to CI. As previously mentioned it's a great tool to run manually once
in a while, but false positives or things done intentionally should not
fail the build each time.
