### ISSUE TITLE
Let ProjectionsManager return objects instead of json-strings

### ISSUE THREAD

**Issue by enumag** [prooph/event-store#390]
I'm wondering about some methods of the ProjectionsManager.

These return ProjectionDetails objects: https://github.com/prooph/event-store/blob/master/src/Async/Projections/ProjectionsManager.php#L67-L86

This one however only returns json: https://github.com/prooph/event-store/blob/master/src/Async/Projections/ProjectionsManager.php#L88-L95

What's the reason? I have some cases where I'd like to get ProjectionDetails object for one specific projection...

**Comment by prolic** [comment]
I migrated this from here https://github.com/EventStore/EventStore/blob/master/src/EventStore.ClientAPI/Projections/ProjectionsManager.cs#L174-L188

But you are right, we can make this return an object. Wanna submit a pull request?

**Comment by Nek-** [comment]
I actually think following their implementation is a great idea.

**Comment by prolic** [comment]
@Nek- What is your use-case? In which scenario you'd rather have a json encoded string instead of an object back?
