### ISSUE TITLE
aggregate_version conflict (ConcurrencyException) when stream on heavy load

### ISSUE THREAD

**Issue by EmilMassey** [prooph/event-store#392]
We encountered problems when appending an event to the store when our app was on relatively heavy load. This has never happened before when events weren't emitted so often.

```
Prooph\\EventStore\\Exception\\ConcurrencyException(code: 0): Some of the aggregate IDs or event IDs have already been used in the same stream. The PDO error should contain more information: Error 23000. Error-Info: Duplicate entry 'App\\Bank\\Model\\Account\\Account-bb34e33d-c93d-45c3-80d9-e312bce2d' for key 'ix_unique_event' at /var/www/vendor/prooph/pdo-event-store/src/Exception/ConcurrencyExceptionFactory.php:22)
```

As `ix_unique_event` is made of `aggregate_type`, `aggregate_id`, `aggregate_version`, I assume it's duplicated aggregate version.

### Some information
Version: `v7.5.6`
Store: `MariaDbEventStore`
Persitence strategy: `MariaDbSingleStreamStrategy`

**Comment by prolic** [comment]
Yes, you have to see how you want to handle this case. Maybe retry, maybe
merge results and retry? Maybe just error and inform the user, that someone
else changed that in the meantime.

There is no general approach to it, you have to decide what's best for your
use case.

**Comment by EmilMassey** [comment]
Thank you for your response.
