### ISSUE TITLE
Tests are missing

### ISSUE THREAD

**Issue by Nek-** [prooph/event-store#394]
Having some unit tests here could be great. WDYT?

Related to #393 (which would have been detected by a test)

**Comment by prolic** [comment]
A pull request is always welcome!

**Comment by unixslayer** [comment]
@prolic this was pretty confusing for me that changes made in this repository must be tested in another one. since this contains only interfaces and VOs, why is it separated from `prooph/event-store-client`? have you considered merging them together?

**Comment by enumag** [comment]
@unixslayer Interfaces are separated because there is a second implementation as well: https://github.com/prooph/event-store-http-client

**Comment by unixslayer** [comment]
@enumag thanks, didn't catch that.

**Comment by evolic** [comment]
So it seems that we can close this issue.
