### ISSUE TITLE
Remove further json strings from managers

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#401]
f.e. `\Prooph\EventStoreClient\Projections\QueryManager::executeAsync`

there is more

/cc @unixslayer - interessted?

**Comment by unixslayer** [comment]
@prolic ofc

**Comment by prolic** [comment]
nice, can't wait for it :+1:

**Comment by unixslayer** [comment]
@prolic this concerns both sync and async methods?

**Comment by enumag** [comment]
@unixslayer yes

**Comment by unixslayer** [comment]
@prolic sory for the delay. I think I finished this issue both in prooph/event-store and proopt/event-store-client and ready for review
