### ISSUE TITLE
PersistentSubscriptionCreateStatus wrongly internal ?

### ISSUE THREAD

**Issue by Nek-** [prooph/event-store#406]
Usage `Prooph\EventStore\Internal\PersistentSubscriptionCreateStatus` of is [documented](https://github.com/prooph/documentation/blob/master/event-store-client/readmodels.md) but this class is tagged as internal.

Idk maybe it's a documentation issue... But creating new instances of PersistentSubscriptionCreateStatus seems to be the best thing to do to check the status of a response.

I didn't check out anything else but other responses may have same issue I guess.

**Comment by prolic** [comment]
Yes, that's a bug, would you submit a PR? Just move the files one namespae above and remove the `@internal` annotation.

**Comment by Nek-** [comment]
Well. You're fast.
