### ISSUE TITLE
Detaching listener handlers from event store

### ISSUE THREAD

**Issue by webdevilopers** [prooph/event-store#410]
Since prooph service bus is deprecated we are using the symfony messenger. In order to couple it we copied the publisher from the original bridge but inject the symfony bus:

* https://github.com/prooph/event-store-bus-bridge/blob/master/src/EventPublisher.php

The publisher attaches some listeners for `append_to`:

```php
    public function attachToEventStore(ActionEventEmitterEventStore $eventStore): void
    {
        $this->listenerHandlers[] = $eventStore->attach(
            ActionEventEmitterEventStore::EVENT_APPEND_TO,
            function (ActionEvent $event) use ($eventStore): void {
                $recordedEvents = $event->getParam('streamEvents', new \ArrayIterator());

                if (! $this->inTransaction($eventStore)) {
                    if ($event->getParam('streamNotFound', false)
                        || $event->getParam('concurrencyException', false)
                    ) {
                        return;
                    }

                    foreach ($recordedEvents as $recordedEvent) {
                        $this->eventBus->dispatch($recordedEvent);
                    }
                } else {
                    $this->cachedEventStreams[] = $recordedEvents;
                }
            }
        );

```

We have a service that is writing directly to the event store and we do not want to publish these events.
We can detach the complete plugin from the event store via:

```php
$this->publisher->detachFromEventStore($this->eventStore);
```

But how could this be achieved using the `detach` method on the event store itself?

We tried this:

```php
        $publisher = new DefaultListenerHandler(function(ActionEvent $event) {
            dump($event);exit;
        });
        $this->eventStore->detach($publisher);
```

But we are not sure how to design the closure. In our example nothing happens.

Any help would be appreciated.

Probably related:

* https://github.com/prooph/event-store/issues/232

**Comment by prolic** [comment]
From the top of my head (on the phone right now): use the return value of
the attach call.

**Comment by webdevilopers** [comment]
Unfort. the `detach` method is in a different class than the `attach` inside the `EventPublisher` class.

The return value dumped looks like this:

![Screenshot from 2020-08-07 11-55-54](https://user-images.githubusercontent.com/3479626/89634134-29c1ed80-d8a5-11ea-9d67-1f9af08fbdf6.png)

I must confess I don't know how to recreate that closure.

**Comment by webdevilopers** [comment]
Any idea - @codeliner maybe?

**Comment by unixslayer** [comment]
@webdevilopers even if you recreate that closure, you will not be able to detach listener.

```php
$actionEventEmitter = new ProophActionEventEmitter();
$eventStore = new ActionEventEmitterEventStore(new InMemoryEventStore(), $actionEventEmitter);

$callable = function (ActionEvent $event) {};

$eventStore->attach('event_name', $callable);
$eventStore->detach(new DefaultListenerHandler($callable)); // this doesn't detach the listener
```

This is due to strict comparison in `ProophActionEventEmitter`

```php
// \Prooph\Common\Event\ProophActionEventEmitter::detachListener
public function detachListener(ListenerHandler $listenerHandler): bool
{
    foreach ($this->events as &$prioritizedListeners) {
        foreach ($prioritizedListeners as &$listenerHandlers) {
            foreach ($listenerHandlers as $index => $listedListenerHandler) {
                if ($listedListenerHandler === $listenerHandler) { // <--- here
                    unset($listenerHandlers[$index]);

                    return true;
                }
            }
        }
    }

    return false;
}
```
Even with weaker comparison still won't work. 
```php
$eventStore->detach(new DefaultListenerHandler(function (ActionEvent $event) {})); // not working
$eventStore->detach(new DefaultListenerHandler($callable)); // might work with loose comparison
```
The only way to detach the listener is to use value returned from attach call, like @prolic described
```php
$listener = $eventStore->attach('event_name', $callable);
$eventStore->detach($listener); // works like a charm
```

**Comment by webdevilopers** [comment]
Thanks @unixslayer for clearing this up. I was really wondering how a closure could be recreated.

In my case the `EventPublisher` is added via Symfony and the `EventStoreBusBridge`:

```yaml
services:
    _defaults:
        public: false

    Prooph\EventStoreBusBridge\EventPublisher:
        class: Rewotec\Common\Infrastructure\Prooph\EventPublisher
        arguments:
            - '@messenger.bus.events'
        tags:
            - { name: 'prooph_event_store.default_store.plugin' }
            - { name: 'prooph_event_store.async_store.plugin' }
```

So I'm missing the actual part:

```php
$eventStore->attach('event_name', $callable);
```

That's why I used this solution so far:

```php
$this->eventPublisher->detachFromEventStore($this->eventStore);
```

This is called in totally different service class, not the configuration of the event store. That's why this is the only reference to the listener I have so far. I guess there is no other way to determine and get the listener then.

**Comment by prolic** [comment]
I'm closing this.
