### ISSUE TITLE
Move EventStoreFactory one namespace level up

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store#69]
Namespace of EventStoreFactory should only be `Prooph\EventStore\Service`.
We should also think up renaming `Service` to `Factory`. 
Putting factories under a `Service` namespace is common practice in ZF2 but maybe this confuses others.

**Comment by codeliner** [comment]
@prolic What do you think regarding the namespace name?

**Comment by prolic** [comment]
Do you want to put all factories in the service namespace or do you want to
get rid of the service namespace?
Am 21.08.2015 08:14 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by codeliner** [comment]
Sorry, my description is confusing (wrote it to early in the morning :smile: )

I would like to put all factories in a `Factory` namespace:

src
|_ Factory
    |_ Stream
        |_ SingleStreamFactory.php
        |_ ...
    |_ EventStoreFactory.php
|_ ...
|_ EventStore.php

**Comment by prolic** [comment]
I am okay with getting rid of the _Service\EventStore_ namespace in favour of only a _Service_ namespace. But I am against the renaming from _Service_ to _Factory_.
ZF2 uses also the _Service_ namespace for their factories, f.e. Zend\Mvc\Service, see: https://github.com/zendframework/zend-mvc/tree/master/src/Service

**Comment by prolic** [comment]
Oh now I see, I put the EventStore factory into the Stream subnamespace, my bad. I'll provide a fix ;)

**Comment by codeliner** [comment]
@prolic yeah, I know that Zend puts factories under the *Service* namespace, but why? A factory is not a service. It provides a service. zend-expressive organizes the factories under a `Container` folder:
https://github.com/zendframework/zend-expressive/tree/master/src/Container

Maybe also a good idea. The problem I have with *Service* is that I expect real services in this namespace, not only factories.
And for prooph/service-bus I chose *Factory*: https://github.com/prooph/service-bus/tree/master/src/Factory

We must use the same namespace for factories in every project. However, if we decide fast I can change service-bus and release a bugfix

**Comment by prolic** [comment]
Well, Container then? :-) You decide.

**Comment by codeliner** [comment]
Why not *Factory*?

**Comment by prolic** [comment]
As I said, you decide, it's probably the most unimportant issue to me ;-)

**Comment by codeliner** [comment]
naming is important, but not always easy. Ok let's use `Container`. Zend uses it so people will look for container factories in a container folder.
I'll update service-bus.

**Comment by prolic** [comment]
done, see: https://github.com/prooph/event-store/pull/73

**Comment by codeliner** [comment]
done too, see: https://github.com/prooph/service-bus/pull/62
