### ISSUE TITLE
Improve set up of AggregateRepository

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store#72]
- [x] ~~We should also provide a factory for the AggregateRepository.~~ -> moved to #89 

- [x] Furthermore, stream strategy should default to SingleStreamStrategy.

That means constructor arguments will change

```php
    /**
     * @param EventStore $eventStore
     * @param AggregateType $aggregateType
     * @param AggregateTranslator $aggregateTranslator
     * @param StreamStrategy|null $streamStrategy
     */
    public function __construct(
        EventStore $eventStore,
        AggregateType $aggregateType,
        AggregateTranslator $aggregateTranslator,
        StreamStrategy $streamStrategy = null
    ) {
```

**Comment by prolic** [comment]
- constructor changed
- single stream strategy is now default

todo: write factory and factory test

**Comment by codeliner** [comment]
@prolic I've updated the description. Would like to schedule the factory for v5.1. It is not a must have atm.
shipping 5.0 has higher priority.
