### ISSUE TITLE
Logo for github

### ISSUE THREAD

**Issue by prolic** [prooph/event-store#86]
We need a nice logo on github.com/prooph

**Comment by MattKetmo** [comment]
What about the one used for github.com/proophsoftware ?

**Comment by codeliner** [comment]
That is the logo of my company ;) prooph software GmbH. It is a sponsor of prooph components as @sandrokeil and me spent some work time on contributing. We will also offer commercial support but prooph components is an independent open source library and needs its own logo. We've decided to use this one: http://prolic.github.io/cqrs-event-sourcing-talk/#/3
But we need to make a small version of it, maybe just the colored hexagon. My graphic department will provide a small version soon and we also want to add it in the docs.

**Comment by basz** [comment]
something like so ?: https://www.dropbox.com/s/d8osf6fid5qqgf1/prooph-logo.ai?dl=0

**Comment by prolic** [comment]
Wow,cool. Thank you. @codeliner ??

Am 02.09.2016 07:15 schrieb "Bas Kamer" <notifications@github.com>:

**Comment by basz** [comment]
If like i can clean it up and prepare a few variants/formats/sizes

**Comment by prolic** [comment]
I like it! That would be great. I hope @codeliner sees this before he goes on vacation, would like to collect his thoughts, too.

**Comment by codeliner** [comment]
As it is extracted from our prooph components image of course I'm ok with it ;) Question is if we can use it as a logo and don't violate any copyrights? We did not have the time to check that. 

If you have ideas for other variants (different colors, different design ...) don't hesitate to suggest them. The image was a first draft not written in stone ;).

**Comment by basz** [comment]
I'm sure at sometime a generic hexagon was copyrighted by some company somewhere. 

Dunno how you can find that out other then via a legal team.

For an open source project I think you can take the chance. Can always change logos when lawyers come knocking...

I'll see if I can come up with some variantions.

**Comment by prolic** [comment]
@basz same thought here about copyright. Thanks for your contributions!

**Comment by codeliner** [comment]
@basz @prolic yeah, you are right. We should take the chance. We don't have a legal team at hand but hey it is open source and we have a colored hexagon :)

> I'll see if I can come up with some variantions.

That would be really great! So that we have maybe 3 variants and can start a small survey to let our community decide which one is the best :) 

I'm off for three and a half weeks starting from today. When I'm back my plan is to continue work on  getprooph.org. A logo is part of this work so your contribution arrived at the right time :)

**Comment by sandrokeil** [comment]
@basz Are you planning to have slight modifications for each component or group like servce-bus, event-store, snapshotter ... ? I'm not sure if it makes sense, just an idea ;-)

**Comment by codeliner** [comment]
@basz Did you find the time to try different colors?
@sandrokeil Yeah, each edge represents a specific topic covered by prooph components. We could move the corresponding edge slightly out of the hexagon when used as logo for a component and the  completed hexagon on getprooph.org, in slides and so on. 
Thoughts?

**Comment by prolic** [comment]
Sounds great

Am 29.09.2016 02:03 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by basz** [comment]
@all dropbox link has been updated...

Sandro Keil @sandrokeil 21:24
@basz awesome  I like the first one of the second row. the current component piece (color) could be lift up or so.

Bas Kamer @basz 21:31
added a label, so we can better discuss it

Sandro Keil @sandrokeil 21:35
what is the difference between variant 7 and 10 ? or is the color wrong on variant 10?

Bas Kamer @basz 21:38
my bad; refresh

Sandro Keil @sandrokeil 21:41
no worries. looks also good.
i like the black variants (7 - 10) too . What do you think about using the shape from variant 4 for this? so the color is the current component, and the others are black, but it looks not like a pill
and variant 13 or 14 with this shape is for all components 
I guess, then we have enough options and @codeliner should take a look

Bas Kamer @basz 21:46
i agree, but I do like the rounded corners from the second column. maybe a bit less rounded… but i feel it makes the thing a bit more friendly. The ‘exploded’ parts (variant 4) i like too...

**Comment by sstok** [comment]
Any but the round ones (they really look like pills or germs 😜), nr. 16 is really strange 🤔

**Comment by basz** [comment]
Hehe :) For nr 16 you must wear a motion graphics hat. That along with a creative hat...

**Comment by codeliner** [comment]
@sstok  @basz "You take the blue pill, the story ends. You wake up in your bed and believe whatever you want to believe. You take the red pill, you stay in Wonderland, and I show you how deep the rabbit hole goes."

**Comment by basz** [comment]
update https://www.dropbox.com/sh/ni31mtvh8qn6n1i/AACHDu4jAeqU4elsYxe4a_r4a?dl=0

**Comment by mablae** [comment]
@basz Wow, nice work. 

Personally I like the variants 5,7,8,9 most. The edge ratio (round border) fits best.

**Comment by sandrokeil** [comment]
@basz The `prooph-03-color.ai` looks awesome (second row). I guess we don't need to lift up the current component shape. I'm also for edge shapes.

**Comment by basz** [comment]
I'm a little confused about the roundedness of the corners we all prefer.

I proposed 
- 1) None (hard edge)
- 2) ~2% (roundedness is optically a hard edge)
- 3) 100% - the pills

I prefer 2 and I believe most of us do... correct?

**Comment by codeliner** [comment]
ok, I'd like to start a final twitter poll for our preferred options for the main logo: if I look through the comments I think we should select option 1, 4 and 5 for the poll.
Once we have a final decision for the main logo, we can do a second poll for the components variant or just agree on a format.

@basz Can you prepare a file with these 3 options (1,4,5)? I'd link the file in the poll. Thx for the great work again!

**Comment by basz** [comment]
ok. Have look at [prooph-04-candidates](https://www.dropbox.com/sh/ni31mtvh8qn6n1i/AACHDu4jAeqU4elsYxe4a_r4a?dl=0) and put them up for vote.

**Comment by codeliner** [comment]
Poll is here: https://twitter.com/prooph_software/status/788447670234976256

**Comment by codeliner** [comment]
VotingFinished -> ExportWinnerLogoAsPng -> WinnerLogoWasExported::by(@basz) -> UploadNewLogo -> LogoWasUploaded -> closeIssue
